spring:
  application:
    name: movie
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs
  datasource:
    name: movie connection pool
    url: jdbc:postgresql://localhost:3305/movie
    username: root
    password: 123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
