openapi: 3.0.3
info:
  title: Movie API
  description: "API contract of the movie API"
  version: "1.0.0"
paths:
  /movie:
    post:
      operationId: create
      tags:
        - movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieDto'

      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        '500':
          description: Internal server error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
  /movie/{movieId}:
    get:
      operationId: view
      tags:
        - movie
      parameters:
        - name: movieId
          in: path
          required: true
          description: The id of the movie to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieDto'

components:
  schemas:
    MovieDto:
      type: object
      properties:
        id:
          type: string
          description: "id of the movie"
        title:
          type: string
          description: "title of the movie"
          minLength: 2
          maxLength: 255
        description:
          type: string
          description: "a short description of the movie"
          minLength: 10
          maxLength: 500
        producer:
          type: string
          description: "name of the producer"
          minLength: 3
          maxLength: 255
        language:
          type: string
          description: "language of the movie"
          minLength: 3
          maxLength: 255
        durationInMinutes:
          type: integer
          description: "length of the movie in minutes"
          maximum: 999
          minimum: 1
      required:
        - title
        - description
        - producer
        - language
        - durationInMinutes
    CommonResponse:
      type: object
      properties:
        message:
          type: string
        id:
          type: string

