version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5555:5432"
    restart: always
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: movie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movie
      SPRING_DATASOURCE_USERNAME: movie_user
      SPRING_DATASOURCE_PASSWORD: 123
